'use strict';

// tests for latest-hours
// Generated by serverless-mocha-plugin

const mochaPlugin = require('serverless-mocha-plugin');
const lambdaWrapper = mochaPlugin.lambdaWrapper;
const expect = mochaPlugin.chai.expect;
let wrapped;

if (process.env.SERVERLESS_MOCHA_PLUGIN_LIVE) {
  const mod = mochaPlugin.initLiveModule('latest-hours');
  wrapped = lambdaWrapper.wrap(mod);
} else {
  const mod = require(process.env.SERVERLESS_TEST_ROOT + '/process/latest-hours/index.js');
  wrapped = lambdaWrapper.wrap(mod, {
    handler: 'handler',
  });
}

describe('latest-hours', () => {
  before((done) => {
//  lambdaWrapper.init(liveFunction); // Run the deployed lambda

    done();
  });

  it('implement tests here', () => {
    return wrapped.run({ type: '3h' }).then((response) => {
      expect(response).to.not.be.empty;
    });
  });

  it('implement tests here', () => {
    return wrapped.run({ type: '6h' }).then((response) => {
      expect(response).to.not.be.empty;
    });
  });

  it('implement tests here', () => {
    return wrapped.run({ type: '12h' }).then((response) => {
      expect(response).to.not.be.empty;
    });
  });

  it('implement tests here', () => {
    return wrapped.run({ type: '24h' }).then((response) => {
      expect(response).to.not.be.empty;
    });
  });
});
